# Kuratiertes Aktien-Universum je Sektor / Megatrend.
# Auswahlkriterium: liquide, bekannte Titel, die ueber Trade Republic (Lang & Schwarz
# Exchange) handelbar sind. US-Ticker ohne Suffix, deutsche Werte mit ".DE".
#
# Dies ist eine kuratierte Startliste, kein Live-Abgleich mit dem tatsaechlichen
# Trade-Republic-Handelsplatzangebot. Bitte gelegentlich pruefen/erweitern.

CATEGORIES = {
    "technologie": {
        "label": "Technologie",
        "type": "sektor",
        "tickers": ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "NVDA", "AVGO", "ORCL",
                    "ADBE", "CRM", "AMD", "INTC", "CSCO", "IBM", "QCOM", "TXN",
                    "NOW", "SAP.DE", "INTU", "PLTR"],
    },
    "gesundheit": {
        "label": "Gesundheit",
        "type": "sektor",
        "tickers": ["LLY", "UNH", "JNJ", "ABBV", "MRK", "PFE", "TMO", "ABT",
                    "DHR", "AMGN", "GILD", "ISRG", "VRTX", "REGN", "BMY", "CVS",
                    "ELV", "SYK", "BSX", "MRNA"],
    },
    "finanzen": {
        "label": "Finanzen",
        "type": "sektor",
        "tickers": ["JPM", "BAC", "WFC", "MS", "GS", "C", "SCHW", "BLK",
                    "AXP", "SPGI", "V", "MA", "PYPL", "ALV.DE", "DBK.DE", "USB",
                    "PNC", "TFC", "ICE", "CB"],
    },
    "zyklischer_konsum": {
        "label": "Zyklischer Konsum",
        "type": "sektor",
        "tickers": ["AMZN", "TSLA", "HD", "MCD", "NKE", "SBUX", "TJX", "LOW",
                    "BKNG", "MAR", "GM", "F", "RCL", "CCL", "ABNB", "EBAY",
                    "YUM", "ROST", "DHI", "LEN"],
    },
    "basiskonsum": {
        "label": "Basiskonsum",
        "type": "sektor",
        "tickers": ["PG", "KO", "PEP", "COST", "WMT", "PM", "MO", "MDLZ",
                    "CL", "KMB", "GIS", "STZ", "EL", "KHC", "ADM", "SYY",
                    "KR", "TGT", "HSY", "CLX"],
    },
    "industrie": {
        "label": "Industrie",
        "type": "sektor",
        "tickers": ["CAT", "HON", "UPS", "RTX", "BA", "GE", "LMT", "DE",
                    "UNP", "MMM", "ETN", "EMR", "ITW", "PH", "NOC", "GD",
                    "WM", "CSX", "NSC", "SIE.DE"],
    },
    "energie": {
        "label": "Energie",
        "type": "sektor",
        "tickers": ["XOM", "CVX", "COP", "SLB", "EOG", "PSX", "MPC", "VLO",
                    "OXY", "WMB", "KMI", "HAL", "BKR", "DVN", "FANG",
                    "TRGP", "APA"],
    },
    "versorger": {
        "label": "Versorger",
        "type": "sektor",
        "tickers": ["NEE", "DUK", "SO", "D", "AEP", "EXC", "SRE", "XEL",
                    "ED", "PEG", "WEC", "ES", "AWK", "PPL", "FE", "ETR",
                    "EIX", "CMS", "DTE", "ATO"],
    },
    "telekommunikation": {
        "label": "Telekommunikation",
        "type": "sektor",
        "tickers": ["T", "VZ", "TMUS", "CMCSA", "CHTR", "DTE.DE", "VOD",
                    "AMX", "LUMN", "IRDM"],
    },
    "grundstoffe": {
        "label": "Grundstoffe",
        "type": "sektor",
        "tickers": ["LIN", "APD", "SHW", "ECL", "FCX", "NEM", "DOW", "DD",
                    "PPG", "NUE", "VMC", "MLM", "ALB", "CE", "IFF", "BAS.DE",
                    "CTVA", "MOS", "CF", "STLD"],
    },
    "immobilien": {
        "label": "Immobilien",
        "type": "sektor",
        "tickers": ["PLD", "AMT", "EQIX", "PSA", "O", "SPG", "WELL", "DLR",
                    "AVB", "EQR", "VICI", "CCI", "EXR", "MAA", "ESS", "VTR",
                    "ARE", "INVH", "UDR", "KIM"],
    },
    "ki": {
        "label": "Kuenstliche Intelligenz",
        "type": "megatrend",
        "tickers": ["NVDA", "MSFT", "GOOGL", "META", "AMD", "PLTR", "SNOW",
                    "CRM", "NOW", "ORCL", "AVGO", "SMCI", "ARM", "DELL",
                    "IBM", "ADBE", "TSM", "ANET", "MRVL"],
    },
    "cybersecurity": {
        "label": "Cybersecurity",
        "type": "megatrend",
        "tickers": ["CRWD", "PANW", "FTNT", "ZS", "OKTA", "S",
                    "QLYS", "TENB", "VRNS", "CHKP", "NET", "DDOG", "RPD",
                    "GEN"],
    },
    "e_mobility": {
        "label": "E-Mobility",
        "type": "megatrend",
        "tickers": ["TSLA", "RIVN", "LCID", "NIO", "GM", "F", "ALB", "ENPH",
                    "CHPT", "BLNK", "PLUG", "STLA", "XPEV", "LI", "QS", "ON"],
    },
}

# Anzeigenamen (vermeidet 250x langsame yfinance .info-Aufrufe pro Lauf)
NAMES = {
    "AAPL": "Apple", "MSFT": "Microsoft", "GOOGL": "Alphabet", "AMZN": "Amazon",
    "META": "Meta Platforms", "NVDA": "Nvidia", "AVGO": "Broadcom", "ORCL": "Oracle",
    "ADBE": "Adobe", "CRM": "Salesforce", "AMD": "AMD", "INTC": "Intel",
    "CSCO": "Cisco", "IBM": "IBM", "QCOM": "Qualcomm", "TXN": "Texas Instruments",
    "NOW": "ServiceNow", "SAP.DE": "SAP", "INTU": "Intuit", "PLTR": "Palantir",
    "LLY": "Eli Lilly", "UNH": "UnitedHealth", "JNJ": "Johnson & Johnson",
    "ABBV": "AbbVie", "MRK": "Merck & Co", "PFE": "Pfizer", "TMO": "Thermo Fisher",
    "ABT": "Abbott", "DHR": "Danaher", "AMGN": "Amgen", "GILD": "Gilead Sciences",
    "ISRG": "Intuitive Surgical", "VRTX": "Vertex Pharmaceuticals", "REGN": "Regeneron",
    "BMY": "Bristol-Myers Squibb", "CVS": "CVS Health", "ELV": "Elevance Health",
    "SYK": "Stryker", "BSX": "Boston Scientific", "MRNA": "Moderna",
    "JPM": "JPMorgan Chase", "BAC": "Bank of America", "WFC": "Wells Fargo",
    "MS": "Morgan Stanley", "GS": "Goldman Sachs", "C": "Citigroup",
    "SCHW": "Charles Schwab", "BLK": "BlackRock", "AXP": "American Express",
    "SPGI": "S&P Global", "V": "Visa", "MA": "Mastercard", "PYPL": "PayPal",
    "ALV.DE": "Allianz", "DBK.DE": "Deutsche Bank", "USB": "US Bancorp",
    "PNC": "PNC Financial", "TFC": "Truist Financial", "ICE": "Intercontinental Exchange",
    "CB": "Chubb", "TSLA": "Tesla", "HD": "Home Depot", "MCD": "McDonald's",
    "NKE": "Nike", "SBUX": "Starbucks", "TJX": "TJX Companies", "LOW": "Lowe's",
    "BKNG": "Booking Holdings", "MAR": "Marriott", "GM": "General Motors",
    "F": "Ford", "RCL": "Royal Caribbean", "CCL": "Carnival", "ABNB": "Airbnb",
    "EBAY": "eBay", "YUM": "Yum! Brands", "ROST": "Ross Stores", "DHI": "D.R. Horton",
    "LEN": "Lennar", "PG": "Procter & Gamble", "KO": "Coca-Cola", "PEP": "PepsiCo",
    "COST": "Costco", "WMT": "Walmart", "PM": "Philip Morris International",
    "MO": "Altria", "MDLZ": "Mondelez", "CL": "Colgate-Palmolive", "KMB": "Kimberly-Clark",
    "GIS": "General Mills", "STZ": "Constellation Brands", "EL": "Estee Lauder",
    "KHC": "Kraft Heinz", "ADM": "Archer-Daniels-Midland", "SYY": "Sysco",
    "KR": "Kroger", "TGT": "Target", "HSY": "Hershey", "CLX": "Clorox",
    "CAT": "Caterpillar", "HON": "Honeywell", "UPS": "UPS", "RTX": "RTX Corporation",
    "BA": "Boeing", "GE": "GE Aerospace", "LMT": "Lockheed Martin", "DE": "Deere & Co",
    "UNP": "Union Pacific", "MMM": "3M", "ETN": "Eaton", "EMR": "Emerson Electric",
    "ITW": "Illinois Tool Works", "PH": "Parker Hannifin", "NOC": "Northrop Grumman",
    "GD": "General Dynamics", "WM": "Waste Management", "CSX": "CSX Corporation",
    "NSC": "Norfolk Southern", "SIE.DE": "Siemens", "XOM": "ExxonMobil",
    "CVX": "Chevron", "COP": "ConocoPhillips", "SLB": "Schlumberger", "EOG": "EOG Resources",
    "PSX": "Phillips 66", "MPC": "Marathon Petroleum", "VLO": "Valero Energy",
    "OXY": "Occidental Petroleum", "WMB": "Williams Companies", "KMI": "Kinder Morgan",
    "HAL": "Halliburton", "BKR": "Baker Hughes", "DVN": "Devon Energy",
    "FANG": "Diamondback Energy", "TRGP": "Targa Resources",
    "APA": "APA Corporation", "NEE": "NextEra Energy",
    "DUK": "Duke Energy", "SO": "Southern Company", "D": "Dominion Energy",
    "AEP": "American Electric Power", "EXC": "Exelon", "SRE": "Sempra",
    "XEL": "Xcel Energy", "ED": "Consolidated Edison", "PEG": "PSEG",
    "WEC": "WEC Energy Group", "ES": "Eversource Energy", "AWK": "American Water Works",
    "PPL": "PPL Corporation", "FE": "FirstEnergy", "ETR": "Entergy",
    "EIX": "Edison International", "CMS": "CMS Energy", "DTE": "DTE Energy",
    "ATO": "Atmos Energy", "T": "AT&T", "VZ": "Verizon", "TMUS": "T-Mobile US",
    "CMCSA": "Comcast", "CHTR": "Charter Communications", "DTE.DE": "Deutsche Telekom",
    "VOD": "Vodafone",
    "AMX": "America Movil", "LUMN": "Lumen Technologies", "IRDM": "Iridium Communications",
    "LIN": "Linde",
    "APD": "Air Products", "SHW": "Sherwin-Williams", "ECL": "Ecolab",
    "FCX": "Freeport-McMoRan", "NEM": "Newmont", "DOW": "Dow Inc",
    "DD": "DuPont", "PPG": "PPG Industries", "NUE": "Nucor", "VMC": "Vulcan Materials",
    "MLM": "Martin Marietta", "ALB": "Albemarle", "CE": "Celanese",
    "IFF": "International Flavors & Fragrances", "BAS.DE": "BASF", "CTVA": "Corteva",
    "MOS": "Mosaic", "CF": "CF Industries", "STLD": "Steel Dynamics",
    "PLD": "Prologis", "AMT": "American Tower", "EQIX": "Equinix",
    "PSA": "Public Storage", "O": "Realty Income", "SPG": "Simon Property Group",
    "WELL": "Welltower", "DLR": "Digital Realty", "AVB": "AvalonBay Communities",
    "EQR": "Equity Residential", "VICI": "VICI Properties", "CCI": "Crown Castle",
    "EXR": "Extra Space Storage", "MAA": "Mid-America Apartment", "ESS": "Essex Property Trust",
    "VTR": "Ventas", "ARE": "Alexandria Real Estate", "INVH": "Invitation Homes",
    "UDR": "UDR Inc", "KIM": "Kimco Realty", "SNOW": "Snowflake",
    "SMCI": "Super Micro Computer", "ARM": "Arm Holdings", "DELL": "Dell Technologies",
    "TSM": "Taiwan Semiconductor", "ANET": "Arista Networks", "MRVL": "Marvell Technology",
    "CRWD": "CrowdStrike", "PANW": "Palo Alto Networks", "FTNT": "Fortinet",
    "ZS": "Zscaler", "OKTA": "Okta", "S": "SentinelOne",
    "QLYS": "Qualys", "TENB": "Tenable", "VRNS": "Varonis Systems",
    "CHKP": "Check Point Software", "NET": "Cloudflare", "DDOG": "Datadog",
    "RPD": "Rapid7", "GEN": "Gen Digital", "RIVN": "Rivian", "LCID": "Lucid Group",
    "NIO": "NIO", "ENPH": "Enphase Energy", "CHPT": "ChargePoint",
    "BLNK": "Blink Charging", "PLUG": "Plug Power", "STLA": "Stellantis",
    "XPEV": "XPeng", "LI": "Li Auto", "QS": "QuantumScape", "ON": "ON Semiconductor",
}


def all_tickers():
    seen = set()
    for cat in CATEGORIES.values():
        for t in cat["tickers"]:
            seen.add(t)
    return sorted(seen)
